version: '3.8'
services: 
    mssql:  
        container_name: sqlserver 
        image: mcr.microsoft.com/mssql/server:latest
        ports:
            - 1433:1433 
        deploy:
             resources: 
                reservations:
                    cpus: '2'
                    memory: '2GB'      
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        volumes:
            - sqldata:/var/opt/mssql
    bazar:        
        container_name: bazar
        build: 
          dockerfile: ./Dockerfile
        domainname: ilianaalexandrova
        image: ilianaalexandrovabazarscr.azurecr.io/bazar    
        ports:
            - '80:80'
        restart: on-failure
volumes:
  sqldata: 
    driver: azure_file
    driver_opts:
        share_name: sql-volume
        storage_account_name: ilianaalexandrovabazarsa
